/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Proveedor;
import Controlador.ProveedorDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    Proveedor pr=new Proveedor();
    ProveedorDAO PrDao=new ProveedorDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    public Proveedores() {
        initComponents();
    }
public void ListarProveedor() {
        List<Proveedor> ListarPr = PrDao.ListarProveedor();
        modelo = (DefaultTableModel) TableProveedor.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarPr.size(); i++) {
            ob[0] = ListarPr.get(i).getId();
            ob[1] = ListarPr.get(i).getRuc();
            ob[2] = ListarPr.get(i).getNombre();
            ob[3] = ListarPr.get(i).getTelefono();
            ob[4] = ListarPr.get(i).getDireccion();
            ob[5] = ListarPr.get(i).getRazonSocial();
            modelo.addRow(ob);
        }
        TableProveedor.setModel(modelo);
    }
    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        TxtDireccionProveedor = new javax.swing.JTextField();
        TxtRazonSocial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabel2Ruc = new javax.swing.JLabel();
        BtnAgregarProveedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnEditarProveedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnEliminarProveedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        TxtRucProveedor = new javax.swing.JTextField();
        BtnCargarProveedores = new javax.swing.JButton();
        TxtNombreProveedor = new javax.swing.JTextField();
        TxtTelefonoProveedor = new javax.swing.JTextField();
        TxtIDProveedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Registrar Proveedor");

        TableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUC", "Nombre", "Telefono", "Direccion", "Razon Social"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProveedor);

        jLabelNombre.setText("Nombre:");

        jLabel2Ruc.setText("RUC");

        BtnAgregarProveedor.setText("Agregar");
        BtnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono:");

        BtnEditarProveedor.setText("Editar");
        BtnEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Direccion:");

        BtnEliminarProveedor.setText("Eliminar");
        BtnEliminarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarProveedorMouseClicked(evt);
            }
        });
        BtnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarProveedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Razon Social:");

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        BtnCargarProveedores.setText("Cargar Proveedores");
        BtnCargarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarProveedoresActionPerformed(evt);
            }
        });

        TxtIDProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabel2Ruc))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel6)
                        .addContainerGap(306, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnAgregarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnCargarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnEditarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(85, 85, 85)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtRucProveedor)
                                .addComponent(TxtNombreProveedor)
                                .addComponent(TxtTelefonoProveedor)
                                .addComponent(TxtDireccionProveedor)
                                .addComponent(TxtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                    .addContainerGap(646, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2Ruc)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelNombre)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIDProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(TxtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(TxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TxtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TxtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TxtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(62, 62, 62)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnAgregarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(BtnCargarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(BtnEditarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(42, 42, 42)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProveedorMouseClicked
        // TODO add your handling code here:
        int fila = TableProveedor.rowAtPoint(evt.getPoint());
        TxtIDProveedor.setText(TableProveedor.getValueAt(fila, 0).toString());
        TxtRucProveedor.setText(TableProveedor.getValueAt(fila, 1).toString());
        TxtNombreProveedor.setText(TableProveedor.getValueAt(fila, 2).toString());
        TxtTelefonoProveedor.setText(TableProveedor.getValueAt(fila, 3).toString());
        TxtDireccionProveedor.setText(TableProveedor.getValueAt(fila, 4).toString());
        TxtRazonSocial.setText(TableProveedor.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_TableProveedorMouseClicked

    private void BtnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        if (!"".equals(TxtRucProveedor.getText()) || !"".equals(TxtNombreProveedor.getText()) || !"".equals(TxtTelefonoProveedor.getText()) || !"".equals(TxtDireccionProveedor.getText())
            || !"".equals(TxtRazonSocial.getText())) {
            pr.setRuc(TxtRucProveedor.getText());
            pr.setNombre(TxtNombreProveedor.getText());
            pr.setTelefono(TxtTelefonoProveedor.getText());
            pr.setDireccion(TxtDireccionProveedor.getText());
            pr.setRazonSocial(TxtRazonSocial.getText());
            PrDao.RegistrarProveedor(pr);
            LimpiarTable();
            LimpiarProveedor();
            ListarProveedor();
            JOptionPane.showMessageDialog(null, "Proveedor Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Alguno de los campos esta vacio");
        }
    }//GEN-LAST:event_BtnAgregarProveedorActionPerformed

    private void BtnEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarProveedorActionPerformed
        // TODO add your handling code here:
        if ("".equals(TxtIDProveedor.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(TxtRucProveedor.getText()) || !"".equals(TxtNombreProveedor.getText()) || !"".equals(TxtTelefonoProveedor.getText())
                || !"".equals(TxtDireccionProveedor.getText()) || !"".equals(TxtRazonSocial.getText())) {
                pr.setRuc(TxtRucProveedor.getText());
                pr.setNombre(TxtNombreProveedor.getText());
                pr.setTelefono(TxtTelefonoProveedor.getText());
                pr.setDireccion(TxtDireccionProveedor.getText());
                pr.setRazonSocial(TxtRazonSocial.getText());
                pr.setId(Integer.parseInt(TxtIDProveedor.getText()));
                PrDao.EditarProveedor(pr);
                LimpiarTable();
                LimpiarProveedor();
                ListarProveedor();
            } else{
                JOptionPane.showMessageDialog(null, "Alguno de los campos esta vacio");
            }
        }
    }//GEN-LAST:event_BtnEditarProveedorActionPerformed

    private void BtnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        if (!"".equals(TxtRucProveedor.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar");
            if (pregunta == 0) {
                int id = Integer.parseInt(TxtRucProveedor.getText());
                PrDao.EliminarProveedor(id);
                LimpiarTable();
                LimpiarProveedor();
                ListarProveedor();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_BtnEliminarProveedorActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // CODIGO PARA QUE REGRESE Al FORMULARIO SISTEMA
        Sistema cerrar = new Sistema ();
        cerrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnCargarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarProveedoresActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarProveedor();
    }//GEN-LAST:event_BtnCargarProveedoresActionPerformed

    private void BtnEliminarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarProveedorMouseClicked
        // TODO add your handling code here:
        int fila = TableProveedor.rowAtPoint(evt.getPoint());
        TxtRucProveedor.setText(TableProveedor.getValueAt(fila, 0).toString());
        TxtNombreProveedor.setText(TableProveedor.getValueAt(fila, 1).toString());
        TxtTelefonoProveedor.setText(TableProveedor.getValueAt(fila, 2).toString());
        TxtDireccionProveedor.setText(TableProveedor.getValueAt(fila, 3).toString());
        TxtRazonSocial.setText(TableProveedor.getValueAt(fila, 4).toString());
        
    }//GEN-LAST:event_BtnEliminarProveedorMouseClicked

    private void TxtIDProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }
        private void LimpiarProveedor() {
        TxtRucProveedor.setText("");
        TxtNombreProveedor.setText("");
        TxtTelefonoProveedor.setText("");
        TxtDireccionProveedor.setText("");
        TxtRazonSocial.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarProveedor;
    private javax.swing.JButton BtnCargarProveedores;
    private javax.swing.JButton BtnEditarProveedor;
    private javax.swing.JButton BtnEliminarProveedor;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JTable TableProveedor;
    private javax.swing.JTextField TxtDireccionProveedor;
    private javax.swing.JTextField TxtIDProveedor;
    private javax.swing.JTextField TxtNombreProveedor;
    private javax.swing.JTextField TxtRazonSocial;
    private javax.swing.JTextField TxtRucProveedor;
    private javax.swing.JTextField TxtTelefonoProveedor;
    private javax.swing.JLabel jLabel2Ruc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
